### ISSUE TITLE
Fastinfernce has no tabular attirbute

### ISSUE THREAD

**Issue by henry090** [muellerzr/fastinference#27]
Hi. The recent version of fastai ```2.1.17``` started throwing a lot of errors. One of them is related to ```fastinference```. 
When I call Shap interpretation, it throws:

```
AttributeError: module 'fastinference' has no attribute 'tabular'
```

**Comment by muellerzr** [comment]
How did you install fastinference?

**Comment by muellerzr** [comment]
Related to: https://github.com/muellerzr/fastinference/issues/21

**Comment by henry090** [comment]
This is the installation: ```pip install fastinference fastinference[interp]```. And I noticed that for fastai 2.1.15 it works fine. But with 2.1.7 I get an error while testing with Github Actions (fresh installation every time).
Fastai 2.1.7 throws errors:

- model summary cannot be printed, again
- dicom file cannot be read. (https://github.com/fastai/fastai/issues/3032)
- AttributeError: module 'fastinference' has no attribute 'tabular'

**Comment by muellerzr** [comment]
The first two are unrelated, this project is separate from fastai. 

You're also installing wrong, it should just be `pip install fastinference[interp]`.

That being said there is some bugs going on so install via:
```python
pip install git+https://github.com/muellerzr/fastinference#egg=fastinference[interp]
```

**Comment by henry090** [comment]
It worked with the dev version of fastinference. Thanks!

**Comment by henry090** [comment]
@muellerzr Hi. Should we clone fastinference from Github every time or it will be on PyPI soon?

**Comment by muellerzr** [comment]
Can you go ahead and try now? It seems I tried to make a release at some point but doesn't look like it went through

**Comment by henry090** [comment]
@muellerzr Yes, this worked with fastai 2.1.8 and  with the installation from Pypi.  Thank you.
